apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odosian
  namespace: odosian
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - odosian.example.com
      secretName: odosian-tls
  rules:
    - host: odosian.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odosian
                port:
                  number: 3000
